title: Contatto
settings:
  confirmation_message: 'Il messaggio Ã¨ stato inviato.'
handlers:
  email_confirmation:
    label: 'Courriel de confirmation'
  email_notification:
    label: 'Notification par courriel'
