label: 'Soumissions de webform'
display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          tags:
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- الكل -'
            offset_label: Décalage
      fields:
        sid:
          separator: ', '
        in_draft:
          label: مسودة
          separator: ', '
        created:
          label: الإنشاء
          separator: ', '
        remote_addr:
          label: 'عنوان الـIP'
          separator: ', '
        view_webform_submission:
          label: عمليات
          text: عرض
      empty:
        area_text_custom:
          content: 'Aucune soumission n''est disponible.'
      arguments:
        in_draft:
          exception:
            title: الكل
      title: 'Soumissions de webform'
  embed_default:
    display_options:
      display_description: 'Afficher les soumissions.'
  embed_administer:
    display_options:
      display_description: 'Administrer les soumissions.'
      fields:
        webform_submission_bulk_form:
          action_title: إجراء
        sid:
          separator: ', '
        in_draft:
          label: مسودة
          separator: ', '
        sticky:
          label: مثبت
          separator: ', '
        locked:
          label: مقفل
          separator: ', '
        created:
          label: الإنشاء
          separator: ', '
        completed:
          label: 'تم الإنهاء'
          separator: ', '
        remote_addr:
          label: 'عنوان الـIP'
          separator: ', '
        operations:
          label: عمليات
      filters:
        in_draft:
          expose:
            label: 'Est un brouillon'
        sticky:
          expose:
            label: مثبت
        locked:
          expose:
            label: مقفل
  embed_manage:
    display_options:
      display_description: 'Gérer les soumissions.'
      fields:
        webform_submission_bulk_form:
          action_title: إجراء
        sid:
          separator: ', '
        in_draft:
          label: مسودة
          separator: ', '
        sticky:
          label: مثبت
          separator: ', '
        locked:
          label: مقفل
          separator: ', '
        created:
          label: الإنشاء
          separator: ', '
        completed:
          label: 'تم الإنهاء'
          separator: ', '
        remote_addr:
          label: 'عنوان الـIP'
          separator: ', '
        view_webform_submission:
          label: عمليات
          text: عرض
        edit_webform_submission:
          label: عمليات
          text: تحرير
      filters:
        in_draft:
          expose:
            label: 'Est un brouillon'
        sticky:
          expose:
            label: مثبت
        locked:
          expose:
            label: مقفل
  embed_review:
    display_options:
      fields:
        sid:
          separator: ', '
        in_draft:
          label: مسودة
          separator: ', '
        sticky:
          label: مثبت
          separator: ', '
        locked:
          label: مقفل
          separator: ', '
        created:
          label: الإنشاء
          separator: ', '
        completed:
          label: 'تم الإنهاء'
          separator: ', '
        remote_addr:
          label: 'عنوان الـIP'
          separator: ', '
        view_webform_submission:
          label: عمليات
          text: عرض
      filters:
        in_draft:
          expose:
            label: 'Est un brouillon'
        sticky:
          expose:
            label: مثبت
        locked:
          expose:
            label: مقفل
