label: Content
description: 'Trouver et gérer le contenu.'
display:
  default:
    display_options:
      title: Content
      fields:
        type:
          label: 'Content type'
        status:
          label: Status
          settings:
            format_custom_false: Unpublished
        changed:
          label: Updated
        operations:
          label: Operations
      pager:
        options:
          tags:
            next: 'Suivant ›'
            previous: '‹ Précédent'
      exposed_form:
        options:
          submit_button: Filter
      empty:
        area_text_custom:
          content: 'Aucun contenu disponible.'
      filters:
        type:
          expose:
            label: 'Content type'
        status:
          expose:
            label: Status
          group_info:
            label: 'Published status'
            group_items:
              2:
                title: Unpublished
        langcode:
          expose:
            label: Language
  page_1:
    display_options:
      menu:
        title: Content
      tab_options:
        title: Content
        description: 'Trouver et gérer le contenu'
