label: Surveillance
description: 'Entrées récentes du journal'
display:
  default:
    display_options:
      title: 'Entrées récentes du journal'
      fields:
        nothing:
          admin_label: Icône
        severity:
          label: Importance
        name:
          label: Utilisateur
        link:
          label: Operations
      exposed_form:
        options:
          submit_button: Filter
      empty:
        area:
          admin_label: 'Aucune entrée du journal n''est disponible.'
          content: 'Aucune entrée du journal n''est disponible.'
      filters:
        severity:
          expose:
            label: Importance
